book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns = [
    path("", views.home, name="home"),
    path("contents", views.contents, name="table of contents"),
    path("<str:book_section>", views.section, name="section"),
]

booksite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("book.urls")),
    path("admin/", admin.site.urls),
]

book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=250, default="no title provided")
    description = models.CharField(max_length=500)
    views = models.IntegerField(default=0)

    # This returns something human readable when you print a queryset
    def __str__(self):
        return self.title

class Section(models.Model):
    section_title = models.CharField(max_length=250)
    section_description = models.CharField(max_length=500,default="")
    section_information = models.TextField(max_length=1000000)
    publish_date = models.DateTimeField()
    book = models.ForeignKey(Book, on_delete=models.PROTECT)
    SECTION_CHOICES = [
        ("A", "System Basics with Rhino"),
        ("B", "Parametric Design with Python and Grasshopper"),
        ("C", "Computational Design Methods")
    ]
    book_section = models.CharField(
        max_length = 2,
        choices = SECTION_CHOICES,
        default = "A",
    )
    sub_sections = models.CharField(
        max_length=1000,
        default=""
    )

    def __str__(self) -> str:
        return self.section_title

    def get_subsections(self):
        delimeter = ","
        single_list = self.sub_sections.split(delimeter)
        paired_list = []
        for x in range(0, len(single_list), 2):
            whitespace = "---"
            repeated_whitespace = whitespace * int(single_list[x])
            paired_list.append([repeated_whitespace, single_list[x + 1], single_list[x + 1].replace(" ", "_")])
        return paired_list

book/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader

from .models import Book, Section

# Create your views here.
def home(request):
    # book_list = Book.objects.all()
    template = loader.get_template("about.html")
    context = {}
    return HttpResponse(template.render(context, request))

def contents(request):
    try:
        this_book = Book.objects.filter(title="Computational Design with Rhino and Grasshopper").first()
        book_sections = this_book.section_set.all()
        template = loader.get_template("table_of_contents.html")
        context = {
            "book" : this_book,
            "sections_list" : book_sections,
        }
    except Book.DoesNotExist:
        raise Http404("Book doesn't exist!")
    return HttpResponse(template.render(context, request))

def section(request, book_section):
    try:
        this_section = Section.objects.filter(section_title=book_section).first()
        template = loader.get_template("section.html")
        context = {
            "section" : this_section,
        }
    except Section.DoesNotExist:
        raise Http404("Book doesn't exist!")
    
    return HttpResponse(template.render(context, request))

book/templates/about.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About The Book</title>
</head>
<body>
    <header>
        <h1>Parametric and Computational Design Methods With Rhino and Grasshopper</h1>
    </header>
    <main>
        
    </main>
    <footer>

    </footer>
</body>
</html>

book/templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books Landing Page</title>
</head>
<body>
    <h1>Welcome to where the books I have written are listed</h1>
    {% if book_list %}
        <ul>
        {% for book in book_list %}
            <li><a href="{% url 'book:table of contents' book.title %}">{{book.title}}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No books are currently available</p>
    {% endif %}
    </body>
</html>

book/templates/section.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if section %}
            {{section.section_title}}
        {% endif %}
    </title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
    <script>
        window.MathJax = {
            tex: {
                inlineMath: [['$','$'], ['\\(', '\\)']], 
                displayMath : [['$$', '$$']]
                },
            };
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'book/section.css' %}" title="section_styles">
    
</head>
<body>
    <header>
        <nav id="top_nav">
            <div id="side_nav_toggle_container">
                <img src="https://ik.imagekit.io/dofkqbm9t/Parametric%20and%20Computational%20Design%20in%20Rhino%20and%20Grasshopper/Site%20Resources/table_of_contents_vector.svg?updatedAt=1691425530976" alt="table_of_contents_toggle" id="toc_toggle_svg">
            </div>
            <div id="section_title_container">
                <h1 id="section_title">
                    {% if section %}
                        {{section.section_title}}
                    {% endif %}
                </h1>
            </div>
            <div id="links_container">
                <div id="home_top_nav_container" class="top_nav_links">
                    <p class="link_text">Home</p>
                </div>
                <div id="toc_top_nav_container" class="top_nav_links">
                    <p class="link_text">Table of Contents</p>
                </div>
                <div id="settings_cog_nav_container" class="top_nav_links">
                    <img src="https://ik.imagekit.io/dofkqbm9t/Parametric%20and%20Computational%20Design%20in%20Rhino%20and%20Grasshopper/Site%20Resources/settings_cog_vector.svg?updatedAt=1691546128066" alt="Settings icon" id="settings_cog_svg">
                </div>
            </div>
        </nav>
        <div id="settings_window">
            <div id="Dark_Mode_Toggle_Container">
                <p id="dark_mode_text">Dark Mode</p>
                <label class="switch" id="dark_mode_switch">
                    <input type="checkbox" id="dark_mode_input">
                    <span id="dark_mode_slider"></span>
                </label>
            </div>
            <div id="font_size_container">
                <p id="font_size_text">Font Size</p>
                <div id="font_size_slider_container">
                    <input type="range" min="6" max="20" value="9" id="font_slider">
                    <p id="font_size_display">6</p>
                </div>
            </div>
        </div>
    </header>
    <main>
        <div id="top_nav_spacer"></div>
        <nav id="side_nav">
            {% for heading, subsection, subsection_id in section.get_subsections %}
                <a href= "#{{subsection_id}}" class="sub_section_link">{{heading}} : {{subsection}}</a><br>
            {% endfor %}
        </nav>
        <div id="main_content_container">
            <div id="main_content">
                {% autoescape off %}
                    {% if section %}
                        {{section.section_information}}
                    {% endif %}
                {% endautoescape %}
            </div>
        </div>
    </main>
    <footer>
        <div>
            <p>A footer with some external and internal links will go here</p>
        </div>
    </footer>
</body>
<script src="{% static 'book/section.js' %}"></script>
</html>

book/templates/table_of_contents.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if book %}
            {{book.title}} Table of Contents
        {% endif %}
    </title>
</head>
<body>
    <header>
        <nav>
            <h1>
                {% if book %}
                    {{book.title}} Table of Contents
                {% endif %}
            </h1>
        </nav>
    </header>
    <main>

    
    {% if sections_list %}
        <ul>
            {% for section in sections_list %}
                <!-- <li><a href="/{{book.title}}/{{section.section_title}}">{{section.section_title}}</a></li>       -->
                <li><a href="{% url 'book:section' section.section_title %}">{{section.section_title}}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    </main>
</body>
</html>